# Usando a imagem de produção do Ruby
FROM ruby:bullseye AS production

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiando os arquivos de código-fonte para o container
COPY . .

# Instalando as gems necessárias para a produção
RUN bundle install --without development test

# Definindo o comando para executar a aplicação (substitua 'start' pelo comando correto)
CMD ["rails", "start"]
