# Usando a imagem de desenvolvimento do Ruby
FROM ruby:bullseye AS development

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiando os arquivos de código-fonte para o container
COPY . .

# Instalando todas as gems, incluindo as de desenvolvimento e testes
RUN bundle install

# Definindo o comando para executar a aplicação em modo de desenvolvimento (substitua 'dev' pelo comando correto)
CMD ["rails", "dev"]
