# Usando a imagem de desenvolvimento do Python
FROM python:bullseye AS development

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiando os arquivos de código-fonte para o container
COPY . .

# Instalando todas as dependências, incluindo as de desenvolvimento
RUN pip install -r requirements.txt

# Definindo o comando para executar a aplicação em modo de desenvolvimento (substitua 'dev' pelo comando correto)
CMD ["python", "app.py"]
