# Usando a imagem de produção do Python
FROM python:bullseye AS production

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiando os arquivos de código-fonte para o container
COPY . .

# Instalando as dependências necessárias para a produção (se houver)
RUN pip install -r requirements.txt

# Definindo o comando para executar a aplicação (substitua 'start' pelo comando correto)
CMD ["python", "app.py"]
