# Usando a imagem de desenvolvimento do Node.js
FROM node:bullseye AS development

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiando os arquivos de código-fonte para o container
COPY . .

# Instalando as dependências de desenvolvimento (não precisa do '--production' aqui)
RUN npm install

# Definindo o comando para executar a aplicação em modo de desenvolvimento (substitua 'dev' pelo comando correto)
CMD ["npm", "run", "dev"]
